version: "3"

services:
  
  nginx:
    build:
      context: .
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/test.conf:/etc/nginx/conf.d/test.conf:ro
      - ./geofile:/usr/shared/geofile:ro
    ports:
      - "8080:80"
      - "8081:81"
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']